# Shortcuts

# Mouse
WHEEL_UP      add volume 2
WHEEL_DOWN    add volume -2
MBTN_RIGHT    script-message-to command_palette show-command-palette "Command Palette"

# Seeking
RIGHT         seek  5 exact
LEFT          seek -5 exact
UP            add volume 2
DOWN          add volume -2

# Frame Step
.             frame-step
,             frame-back-step

# Subtitles
r             script-binding autosub/download_next_provider
S             script-binding autosub/sync_subtitles
v             cycle sub-visibility
z             add sub-delay -0.1
x             add sub-delay +0.1
Z             add sub-delay -1.0
X             add sub-delay +1.0

# Audio Delay
Ctrl+z        add audio-delay -0.1
Ctrl+x        add audio-delay  0.1

# Speed
[             multiply speed 1/1.1
]             multiply speed 1.1
{             set speed 1.0

# Playback
l             ab-loop
T             cycle ontop

# Stats & Screenshots
i             script-binding stats/display-stats-toggle
s             screenshot
Shift+c       screenshot video

# Scripts
Alt+b         script-binding sponsorblock/sponsorblock
Shift+Enter   script-binding playlistmanager/showplaylist
Ctrl+Shift+P  script-message-to command_palette show-command-palette "Command Palette"
Ctrl+n        af toggle dynaudnorm=f=75:r=0.9:p=0.5

# Media Keys
PLAY         cycle pause
PAUSE        cycle pause
PLAYPAUSE    cycle pause
PLAYONLY     set pause no
PAUSEONLY    set pause yes
NEXT         playlist-next
PREV         playlist-prev
STOP         stop
FORWARD      seek 60
REWIND       seek -60
