# Mouse wheel volume control
WHEEL_UP      add volume 2
WHEEL_DOWN    add volume -2

# Arrow keys for exact seeking (skipping standard time-based keyframes)
RIGHT         seek  5 exact
LEFT          seek -5 exact
UP            seek  60
DOWN          seek -60

# Reload scripts quickly
r script-binding autosub/download_subs
S script-binding autosub/sync_subtitles
