# Mouse wheel volume control
WHEEL_UP      add volume 2
WHEEL_DOWN    add volume -2

# Arrow keys for exact seeking (skipping standard time-based keyframes)
RIGHT         seek  5 exact
LEFT          seek -5 exact
UP            seek  60
DOWN          seek -60

# Reload scripts quickly
r script-binding autosub/download_subs
S script-binding autosub/sync_subtitles

# Playback Speed
[ multiply speed 1/1.1
] multiply speed 1.1
{ set speed 1.0

# Manual Subtitle Sync (Shift for bigger jumps)
z add sub-delay -0.1
x add sub-delay +0.1
Z add sub-delay -1.0
X add sub-delay +1.0

# Information & Screenshots
i script-binding stats/display-stats-toggle
s screenshot
c screenshot video # clean screenshot (no subs/OSD)
