# Video Output
profile=gpu-hq
vo=gpu
hwdec=auto-safe      # Use hardware decoding

# Subtitles
sub-auto=fuzzy       # Load external subtitles matching the video filename
sub-file-paths=subs:subtitles  # Look for subs in these subdirectories
slang=en,eng         # Default language preference
blend-subtitles=yes  # Blend subtitles to screen resolution

# Volume & Audio
volume-max=150       # Allow volume up to 150%
alang=en,eng         # Audio language preference

# UI / OSD
osd-font="JetBrainsMono Nerd Font"
osd-font-size=30
osd-border-size=1

# Screenshots
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-directory="~/Pictures/Screenshots/"
screenshot-template="%F-%wH.%wM.%wS"
